### ISSUE TITLE
Doesn't support relative urls in sourcemaps

### ISSUE THREAD

**Issue by stalniy** [rollbar/rollbar-cli#15]
my source map urls are generated relatively to js file and scanner produces the wrong `mappedFile` path:

```js
//# sourceMappingURL=file.js.map
```

the problematic line - https://github.com/rollbar/rollbar-cli/blob/master/src/sourcemaps/scanner.js#L46

**Comment by toddiuszho** [comment]
I have relative source maps like the pattern you cite, but do not have any problems. I checked to make sure files like a/b/c.js with sourceMappingURL=c.js.map were correctly uploaded as min-mapping to https://url-prefix/a/b/c.js

**Comment by stalniy** [comment]
It’s probably my mistake because I tried to upload server side source maps. However rollbar supports remapping without sending it to rollbar servers. 

So, let’s close this one.
